### ISSUE TITLE
Failed to compile generated method reader - falling back to proxy method reader

### ISSUE THREAD

**Issue by dave5595** [OpenHFT/Chronicle-Wire#595]
Hi guys, I'm getting this warning when deploying a Springboot application with Chronicle Wire/Queue. 

`Failed to compile generated method reader - falling back to proxy method reader. Please report this failure as support for proxy method readers will be dropped in x.25.
`

Once I have copied the generated code to my project it starts without any warnings. I'm using Kotlin with Gradle compiling it to Java 17 and my version of chronicle-bom is 2.23ea117. I do not have this issue with non Springboot applications which are using the same chronicle-bom and java version stated above.

The only config that I am aware of to get Springboot to play nicely with wire is to include `requiresUnpack("**/chronicle-*.jar")` in the bootjar task, to which I have already included in my Gradle file.

![image](https://user-images.githubusercontent.com/21970743/202097520-a269a4ec-7f8e-4032-b892-867fe5812f33.png)

Just curious as to why this process is manual with Springboot

**Comment by JerryShea** [comment]
@dave5595 I think you have already found the documentation - https://github.com/OpenHFT/Chronicle-Wire#spring-boots-and-dynamic-compilation-in-chronicle-wire - which explains the work around to allow dynamic compilation when using Spring boot's class loading. 

Closing as the issue tracker is for defects or enhancements rather than questions.
