### ISSUE TITLE
Improve handling of binary data in TextWire

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#60]

**Comment by RobAustin** [comment]
@peter-lawrey correct me if I'm wrong, but one use case for this task is to get the DumpQueue to work for the output of the perf test for chronicle services, my understanding is that this is not currently rendering fully as text, some parts are dumping out as binary, and the objective of this issue is to get the whole thing to dump as text. ( is this correct  ? )

**Comment by peter-lawrey** [comment]
The objective here is for binary data in Bytes eg public keys to be read as
well as dumped as Base64. The dumping was working but not the reading. The
unit tests for this are now working.

**Comment by peter-lawrey** [comment]
This would require changes to queue to have more knowledge about which data
types were used to store the data so they could be deserialized.

**Comment by RobAustin** [comment]
@peter-lawrey Is there an example of a failing test  ?

**Comment by RobAustin** [comment]
I feel that this has now been address by using the methodId for data in bytes so closing this issue. The dumping of this as text also works if you provide the appropriate plugin.

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-1.16.0 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-1.16.0), BOM-1.16.8 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.8)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
