### ISSUE TITLE
ServiceCfg fails to read it's own YAML

### ISSUE THREAD

**Issue by maxim-ponomarev** [OpenHFT/Chronicle-Wire#824]
Reproduced in [e685f9e](https://github.com/OpenHFT/Chronicle-Wire/commit/e685f9e7994d98ca12768edf38557f6243eaea21) (`824-servicesCfg-to-yaml-and-back`)

**Comment by peter-lawrey** [comment]
This works with WireType.TEXT as the reader. It's a bug in YAML_ONLY parsing.

**Comment by peter-lawrey** [comment]
The problem is a workaround for detecting if a value is a marshallable or a string, rewinding the bytes and trying again. This strategy can't be supported in YAML as it's stateful and rewinding isn't enough.
The solution is to support converting from text to an object in wire. This will require a change in services.

**Comment by peter-lawrey** [comment]
c.f. https://github.com/OpenHFT/Chronicle-Wire/pull/826
